---
title: "Untitled"
author: "Halid Kopanski"
date: "4/12/2022"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(scales)
library(cowplot)
```

## Problem 1 a)

```{r, message=FALSE, error=FALSE, warning=FALSE}
set.seed(1)

theta_0 <- 0
theta_a <- c(0.1, 0.4, 0.7, 1)

alpha <- 0.05

Y1 <- runif(10000, theta_0, theta_0 + 1)
Y2 <- runif(10000, theta_0, theta_0 + 1)

Y3 <- Y1 + Y2

for (i in 1:4){
    YA <- runif(10000, theta_a[i], theta_a[i] + 1)
    df_Y <- tibble(Y1, Y2, Y3, YA)
    
    plot_ <-
    ggplot(data = df_Y) + 
    geom_density(aes(Y1), fill = "yellow", alpha = 0.5) + 
    geom_area(
    aes(x = stage(Y1, 
                  after_stat = oob_censor(x, (1 - alpha)))),
        stat = "density") + 
    
    geom_density(aes(YA), fill = "blue", alpha = 0.25) + 
    geom_area(
    aes(x = stage(YA, after_stat = oob_censor(x, c(0, (1 - alpha))))),
    stat = "density", fill = "orange", alpha = 0.75) + xlab("") + xlim(-1, 2)
    
    print(plot_)
    }
```

## Problem 1 b)

```{r message=FALSE, error=FALSE, warning=FALSE}
set.seed(1)

theta_0 <- 0
theta_a <- c(0.1, 0.4, 0.7, 1)

c <- 1.684

Y1 <- runif(10000, theta_0, theta_0 + 1)
Y2 <- runif(10000, theta_0, theta_0 + 1)

Y3 <- Y1 + Y2

for (i in 1:4){
    YA1 <- runif(10000, theta_a[i], theta_a[i] + 1)
    YA2 <- runif(10000, theta_a[i], theta_a[i] + 1)

    YA <- YA1 + YA2
    df_Y <- tibble(Y1, Y2, Y3, YA)
    
    plot_ <-
    ggplot(data = df_Y) + 
    geom_density(aes(Y3), fill = "yellow", alpha = 0.5) + 
    geom_area(
        
    aes(x = stage(Y3, 
                  after_stat = oob_censor(x, c))),
                  stat = "density") + 
    
    geom_density(aes(YA), fill = "blue", alpha = 0.25) + 
    geom_area(
        aes(x = stage(YA, after_stat = oob_censor(x, c(0, c))
                     )
           ), 
                      stat = "density", 
            fill = "orange", 
            alpha = 0.75) + 
        xlab("") + xlim(-1, 5)
    
    print(plot_)
    }
```

## Problem 2

```{r}
no_accidents <- c(1735, 1657, 1812, 1962, 1965, 1849, 1755, 
                  1892, 1796, 1900, 1846, 1757)

no_days <- c(31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31)

df_accident <- tibble(month.name, no_accidents, no_days)
colnames(df_accident) <- c("Month", "Observed", "Number of days/Month")

df_accident["daily_ave"] <- df_accident[, 2] / df_accident[, 3]

ave_day <- sum(df_accident["Observed"]) / 365

df_accident["daily_ave_delta"] <- df_accident[, 4] - ave_day

df_accident["Expected"] <- round(ave_day * df_accident[, 3])

df_accident["Observed - Expected"] <- 
  df_accident["Observed"] - df_accident["Expected"]

df_accident["Probs"] <- 
  df_accident["Observed - Expected"]^2 / sum(df_accident["Observed"])

df_accident

X_2 = sum(df_accident["Probs"])
print(X_2)
print(qt(0.95, 12 - 1 - 1))
```

We reject the null hypothesis because the observed test statstic is greater than the calculated value at an alpha level of 0.05. Our observed statistic is `r X_2` which is greater than `r qt(0.95, 12 - 1 - 1)`.

```{r}
plot(df_accident$daily_ave_delta, type = "h", xaxt = "n", xlab = "", 
     ylab = "Difference from Average")
axis(1, at = 1:12, labels = df_accident$Month)
abline(h = 0)
```

July and the winter months seem to indicate a drop in the number of accidents. 

## Problem 3

```{r}
options(repr.plot.width = 5, repr.plot.height = 5, repr.plot.res = 225)

fin_data <- c(110,15,60,54,19,115,73,190,57,43,44,18,37,43,55,19,23,82,175,50,
              80,65,63,36,16,10,17,52,43,70,22,95,20,41,17,15,12,11,29,29,61,22,
              40,17,26,30,16,116,28,32,33,29,27,16,55,8,11,49,82,85,20,67,27,44,
              16,6,35,17,26,32,76,150,21,5,6,51,75,23,29,64,22,47,9,10,28,18,84,
              52,130,50,45,12,21,73)

fin_data <- sort(log(fin_data))

n_fin <- length(fin_data)

lnorm_data <- sort(rlnorm(n_fin, meanlog = mean(fin_data), 
                          sdlog = sqrt(var(fin_data))))

plot(x = fin_data, y = lnorm_data, pch = 20, 
     xlab = "Log Fin Data", ylab = "Log Normal Data")

abline(lm(lnorm_data ~ fin_data), col = "red")
```

## Problem 4

```{r}

data <- c(12.05,12.58,10.06,14.87,12.88,10.7,13.34,13.16,12.93,11.76,12.68,
          13.69,12.3,13.41,11.61,11.44,11.76,12.25,12.43,12.51,12.96,12.27,
          12.34,12.81,13.18,12.46,11.11,12.19,11.97,12.99,12.53,12.19,11.82,
          11.46,13.09,12.1,11.42,12.55,12.08,12.4,11.88,13.25,11.51,11.43,
          12.8,11.79,12.7,13.25,11.53,12.65,13.06,12.21,11.74,12.35,13.27,
          12.91,12.01,12.22,12.35)

# plots
options(repr.plot.width = 12, repr.plot.height = 5, repr.plot.res = 225)

par(mfrow = c(1, 3))

ecdf_plot <- plot(ecdf(data), xlab = "Percent Hydrocarbon in Beeswax", 
                  main = "Beeswax Hydrocarbon Composition", pch = ".")
hist_plot <- hist(data, breaks = 12, main = "Beeswax Hydrocarbon Composition", 
                  xlab = "Percent Hydrocarbon in Beeswax")
qq_plot <- qqnorm(data, pch = 20, main = "Beeswax Normal QQ Plot")
           qqline(data, col = "red")

# Find Quantiles

print(quantile(data, probs = c(0.9, 0.75, 0.5, 0.25, 0.1)))

```

## Problem 5

```{r}
df_data <- read_csv("oldfaithful.csv")
str(df_data)
hist(df_data$DURATION, breaks = 12)
hist(df_data$INTERVAL, breaks = 15)

ggplot(data = df_data, aes(df_data$INTERVAL)) + 
geom_density(fill = "blue", alpha = 0.5) +
xlim(35, 105)

ggplot(data = df_data) + 
geom_density(aes(df_data$DURATION), fill = "red", alpha = 0.5) + 
xlim(0, 6)

plot(x = df_data$INTERVAL, y = df_data$DURATION)
abline(lm(df_data$DURATION ~ df_data$INTERVAL))

df_data %>% group_by(DAY) %>% summarise(int_avg = mean(INTERVAL), dur_avg = mean(DURATION), cnt = length(DAY))

```

